version: 2
updates:
  - package-ecosystem: "github-actions"
    on:
      push:
      pull_request:
        types: [opened]
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    on:
      push:
      pull_request:
        types: [opened]
    directory: "/"
    schedule:
      interval: "weekly"
